### ISSUE TITLE
replace images with text 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#110]
Pulashti emailed this to bo on 

October 4th

Bo - Docker Spark section, update section and make sure to replace images with normal text.

- [x] Stays image as jupyter NB demo. This should be done by Oct 17, 2018. Please take a look: https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-spark.md

are there other files where we need to replace thinsg?

**Comment by laszewsk** [comment]
what is progress?

**Comment by laszewsk** [comment]
look for screenshots that should actually not be screenshots, but copy paste ASCII text.

**Comment by bfeng** [comment]
This should be done by Oct 17, 2018. Please take a look: https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-spark.md

**Comment by laszewsk** [comment]
has this been verified for all text?including 222

**Comment by bfeng** [comment]
I can't find any section with code screenshots for both the cloud and 222 ebooks. If you can find one, please just let me know.
