### ISSUE TITLE
Check and redo Docker Hadoop 3.0.1 and Docker for Hadoop section.

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#115]
This task was e-mailed to Bo on Oct. 4th to be done on that day.

**Comment by laszewsk** [comment]
Gregor found the task was not done and looke into it. Fugang and Gregor replaced 3.0.1 with 3.0.3. They also updated the Java install. However they did not test this. This is for Bo to do

**Comment by bfeng** [comment]
#190 and 46972972a2894b76ef8375e8faa8bc72f65c4505 fixed this issue.
