### ISSUE TITLE
Bigadata lectures

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#116]
identify all lectures in the big data epub in 

https://github.com/cloudmesh-community/book/tree/master/chapters/bigdata

That do not have any videos, find the videos in youtube and add them, modify the videos to update the date. Geoffrey has send many e-mails about this.

**Comment by bfeng** [comment]
Missing videos

* bigdata/algorithms/clustering.md
* bigdata/algorithms/technology.md
