### ISSUE TITLE
REST example may be broken

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#132]
cpu example may be missing th function call registration

not sure why ....

see https://github.com/cloudmesh-community/book/edit/master/chapters/rest/swagger-codegen.md

**Comment by fugangwang** [comment]
This should be no problem.
For this simple example we may not need that. A default function call name will always be generated and automatically bound to the defined REST call. If the students follow the example, they will see the cpu_get() automatically generated which they should modify with the actual implementation also found in the example.

**Comment by laszewsk** [comment]
can you point me to an example where we do this. we point to the cpu example form a later chapter to excplicitly comment on that feature

**Comment by fugangwang** [comment]
The operationId is an optional feature in OpenAPI. We have a separate section that summarizes the OpenAPI specs in which we mentioned the operationId feature. See:
https://github.com/cloudmesh-community/book/blob/master/chapters/rest/swagger-spec.md
