### ISSUE TITLE
internal: Upload lecture videos from Prof Fox's Google Drive to Youtube

### ISSUE THREAD

**Issue by bfeng** [cloudmesh-community/book#152]
- [x] Videos of Spark lectures
- [x] Videos of Hadoop/Mapreduce lectures

**Comment by laszewsk** [comment]
has this been completed?

**Comment by bfeng** [comment]
- https://www.youtube.com/playlist?list=PLy0VLh_GFyz9wDWtaWrHR3XdRTtSylZsu
- https://www.youtube.com/playlist?list=PLy0VLh_GFyz_fQHKynzjfy36KzxImUj1s


Video links updated: 4c1285a90344761b5c294b7d534f5d7fed38406e
