### ISSUE TITLE
internal: Hadoop 3.1.1

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#190]
A student noticed that the hadoop section is outdated. pleas update.

3.0.1 has been removed by apache
3.0.3 is the lates in the 0 which we have not tested.

however 3.1.1 is the newest release 

I suggest to try 3.1.1 before 3.0.3, and if this works update the appropriate sections

there is also a duplicated section on hadoop which we must evaluate and integrate into a single hadoop section

**Comment by laszewsk** [comment]
../chapters/hadoop/hadoop-installation.md
../chapters/mapreduce/hadoop-installation.md

**Comment by laszewsk** [comment]
Bo Pulashti, one of you needs to verify

Also we want to only have the text in mapreduce folder. please verify if text from hadoop folder needs to be copied into the appropriate file

**Comment by btpope** [comment]
No need to copy the text from the hadoop section I'm proposing to remove.  The mapreduce section has everything required.  

Let me know if you need any information from me on this one.

**Comment by bfeng** [comment]
46972972a2894b76ef8375e8faa8bc72f65c4505 this commit fixed the issue.
