### ISSUE TITLE
internal: Virtual machine .md file is missing

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-community/book#227]
sec:virtualbox

**Comment by laszewsk** [comment]
we have  in cloud  

qemu.md
vagrant.md
virsh.md
virtualbox.md
virtualization.md

is is virtualbox.md? or virtualization.md?

**Comment by tbalson** [comment]
1/07 in syllabus the link is dead it just takes you to the quick start page. The links were already deleted so I can't find which file sec:virtualbox is cross referenced too.
