### ISSUE TITLE
internal: piazza scribe for 222

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-community/book#237]
Post python summary for week of 1/5 class and lab

motivate for next week 

requirement.txt 
pip install .

**Comment by laszewsk** [comment]
have students deliver a contribution to the python document on what this is and how to do this. Make sure they do not just copy paste, explain plagiarism.

have them do their own simple requirements and pip install .   or pip install -e . have one student group describe the different between . and -e and add it to the chapter.
