### ISSUE TITLE
Internal: Github video use 

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-community/book#266]
Find video from Spring 2018 or shoot new video showcasing github use with online GUI and command line i.e. syncing upstream etc etc

**Comment by tbalson** [comment]
The video is complete, could use some clean up but is posted here: https://youtu.be/8wyTtG0PsgM

Needs to be integrated into handbook.

**Comment by laszewsk** [comment]
Please find location where they should be posted, look at the preface for example in 516
