### ISSUE TITLE
Test new install-ubuntu.sh script

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#284]
test out the new ubuntu install mechanism as documented in the handbook and fix the install-ubuntu.sh script to make it work.

I have only guessed how it potentially could be done, but not at all tested.

**Comment by tbalson** [comment]
I can try and take a look at this later tonight.

**Comment by tbalson** [comment]
Current error on a fresh ubuntu 18.04 install after running the *.sh script


Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?

**Comment by laszewsk** [comment]
soem TA need to complete the install script so it works, or a student should contribute

**Comment by tbalson** [comment]
Pulasthi have you been able to take a look at this?

When I execute the commands one by one it seems that that after pandoc-2.5 is unpacked and you enter the dir running stack init fails with the following error: 

cabal: internal error when reading package index: failed to parse .cabal
fileThe package index or index cache is probably corrupt. Running cabal update
might fix it.

ok so try 'stack solver' and it fails stack init with a similar error. 

I am currently reading about this but don't have that much time today.

**Comment by tbalson** [comment]
https://github.com/commercialhaskell/stack/issues/4408

**Comment by laszewsk** [comment]
also to install python and haskell (i use 18.10) we need to do 

sudo apt-get install -y python3.7-dev
sudo apt-get install -y python3.7-venv

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 10
sudo update-alternatives --config python3

sudo apt-get install haskell-platform -y
sudo wget -qO- https://get.haskellstack.org/ | sh

**Comment by laszewsk** [comment]
maybe we can install pandoc 2.5 via cabal and not from source. source seems to hang 

not sure if this woudl work

cabal install cabal-install
cabal update
cabal install pandoc
cabal install pandoc-citeproc
cabal install pandoc-crossref

**Comment by tbalson** [comment]
source hangs but eventually proceeds..takes about 20 minutes on my VM maybe a bit more

**Comment by tbalson** [comment]
I think it is working (sh *.sh) Pulasthi can you confirm? Or any other TA...I spun up a new VM and tested it takes about 30/40 minutes. 

Once the script is ran AND
Once the book is cloned ...the old way of making i.e. cd cloud / make new / fails with 

make: *** No rule to make target 'chapterlist', needed by 'prepare'.  Stop

**Comment by tbalson** [comment]
I have successfully ran the *.sh script. It seems to exit cleanly. (On a clean ubuntu 18.04 VM) 

I then checkout book.

cd book
pip install -r requirements.txt
cd cloud 
make clean
make 

or cd book
make clean (no target)
make

My current setup is failing to make with this error: 

../Makefile.book:142: recipe for target 'epub' failed
make: *** [epub] Error 127

**Comment by tbalson** [comment]
yes i know sorry for the lack of clarity I have been cd book/cloud make

**Comment by pulasthi** [comment]
Closing as the using the docker container for making the epubs are used now.
