### ISSUE TITLE
Class enrollment

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#294]
The following students have not accepted their github invitations

private create a student spreadsheet in which you verify
a) student in canvas
b) student in github properly accepted the invitation
c) student posted bio
d) student has notebook.md file
e) student has README.yml

- [ ] sp19-222-97
- [ ] sp19-222-98
- [x] sp19-516-120 deleted
- [x] sp19-516-124
- [ ] sp19-516-126
- [ ] sp19-516-127
- [ ] sp19-516-131
- [ ] sp19-516-133
- [x] sp19-616-110 deleted

**Comment by pulasthi** [comment]
Contacted all students with missing updates and sent out a piazza message to the class. WIll update with progress
