### ISSUE TITLE
internal: cms commands 

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-community/book#318]
Confirm readme works at: https://github.com/cloudmesh/cloudmesh.cmd5
Use sys so create a new command cloudmesh.NEWCOMMAND (make sure this works both ways i.e. pip and source)

- [x] Install from source 
- [x] install using pip 
- [x] integrate into manual pages/sphinx what we have filed here, as its likely not yet in the manual
- [x] integrate new trace logic in the manual page, sphinx
- [x] document the cms sys generate COMMAND in sphinx
- [x] test the cms sys generate COMMAND in sphinx
- [x] document the admin mongo commands (not everything is implemented
       - [ ] start
       - [ ] stop
       - [ ] status
       - [ ] other commands add here
- [x] test the admin mongo commands

**Comment by tbalson** [comment]
simply doing the
```
pip install cloudmesh.cmd5 
```

**Comment by tbalson** [comment]
```
git clone https://github.com/cloudmesh/cloudmesh.common.git
git clone https://github.com/cloudmesh/cloudmesh.cmd5.git
git clone https://github.com/cloudmesh/cloudmesh.bar.git
git clone https://github.com/cloudmesh/cloudmesh.sys.git
cd cloudmesh.common/
python setup.py install
pip install .
ls
cd ..
ls
cd cloudmesh.cmd5/
python setup.py install
pip install .
cd ..
ls
cd cloudmesh.sys/
python setup.py install
pip install .
```

**Comment by laszewsk** [comment]
this needs to be tested, i do not yet understand the errors you see as i do not see them

cms sys generate tyler

will generate cm5 template

cd cloudmesh.tyler
pip install .

installs command tyler

**Comment by tbalson** [comment]
Yes it installs, however what happens when you launch cms? After you generate the new command?

**Comment by laszewsk** [comment]
for me it works

i get the spash screen

**Comment by laszewsk** [comment]
and when i do the tyler command i get the new command registered ,

you can see it with cms help

**Comment by laszewsk** [comment]
I have it working like this

export SRC=`pwd`
git clone https://github.com/cloudmesh/cloudmesh.common.git
git clone https://github.com/cloudmesh/cloudmesh.cmd5.git
git clone https://github.com/cloudmesh/cloudmesh.sys.git
git clone https://github.com/cloudmesh-community/cm.git

cd $SRC/cloudmesh.common
pip install -e .
cd $SRC/cloudmesh.cmd5
pip install -e .
cd $SRC/cloudmesh.sys
pip install -e .
cd $SRC/cm
pip install -e .

**Comment by tbalson** [comment]
will test this way right now.

**Comment by tbalson** [comment]
Ok this is working.

I am not sure what was breaking before. I created a clean virtual env 3.7.1 and followed the above exactly.

then 

cms sys generate tyler
cd cloudmesh.tyler
pip install .

```
cms help tyler 
```
Gives the man page.

**Comment by tbalson** [comment]
These steps work.
```
export SRC=pwd
git clone https://github.com/cloudmesh/cloudmesh.common.git
git clone https://github.com/cloudmesh/cloudmesh.cmd5.git
git clone https://github.com/cloudmesh/cloudmesh.sys.git
git clone https://github.com/cloudmesh-community/cm.git

cd $SRC/cloudmesh.common
pip install -e .
cd $SRC/cloudmesh.cmd5
pip install -e .
cd $SRC/cloudmesh.sys
pip install -e .
cd $SRC/cm
pip install -e .
```
Now create a new command
```
cd $SRC
cms sys generate tyler
cd cloudmesh.tyler
pip install .
cms help tyler 
```

**Comment by laszewsk** [comment]
That’s a bug in git

It needs to be `pwd`

**Comment by laszewsk** [comment]
i fixed the `pwd` as it got lost during copy

**Comment by laszewsk** [comment]
this has drastically changed with cloudmesh-installer

**Comment by laszewsk** [comment]
The instalation process has been replaced with cloudmesh-installer to make it easier. please look at thet manual in cloudmesh-manual
