### ISSUE TITLE
images not found 

### ISSUE THREAD

**Issue by tbalson** [cloudmesh-community/book#432]
pandoc-citeproc: reference www-developer-box not found
[WARNING] Could not fetch resource 'images/unified-types-diagram.png': PandocResourceNotFound "images/unified-types-diagram.png"
[WARNING] Could not fetch resource 'images/documentdb-0.png': PandocResourceNotFound "images/documentdb-0.png"
[WARNING] Could not fetch resource 'images/documentdb-1.png': PandocResourceNotFound "images/documentdb-1.png"
[WARNING] Could not fetch resource 'images/documentdb-2.png': PandocResourceNotFound "images/documentdb-2.png"
[WARNING] Could not fetch resource 'images/documentdb-3.png': PandocResourceNotFound "images/documentdb-3.png"
[WARNING] Could not fetch resource 'images/documentdb-4.png': PandocResourceNotFound "images/documentdb-4.png"
[WARNING] Could not fetch resource 'images/documentdb-5.png': PandocResourceNotFound "images/documentdb-5.png"
[WARNING] Could not fetch resource 'images/documentdb-9.png': PandocResourceNotFound "images/documentdb-9.png"
[WARNING] Could not fetch resource 'images/documentdb-6.png': PandocResourceNotFound "images/documentdb-6.png"
[WARNING] Could not fetch resource 'images/documentdb-7.png': PandocResourceNotFound "images/documentdb-7.png"
[WARNING] Could not fetch resource 'images/documentdb-8.png': PandocResourceNotFound "images/documentdb-8.png"

**Comment by bfeng** [comment]
Images are all found.
Except for this reference:
pandoc-citeproc: reference www-developer-box not found

**Comment by tbalson** [comment]
reference taken care of it was in box.md
