### ISSUE TITLE
Internal: Hot cold isles in data center

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#47]
develop a section about hot cold isles in the data center.

Anthony started on this

Gregor added more suggestions for the section for possible add ons. Ideally the add ons need to be done by a student. If a sudent does not add images Pulashti will do

**Comment by laszewsk** [comment]
added more suggestions for the section for possible add ons. Ideally the add ons need to be done by a student. If a sudent does not add images Pulashti will do

**Comment by robludwig** [comment]
I'd like to do this section

**Comment by pulasthi** [comment]
I added an image and some information on containment. @robludwigI think another student @anthonyduer has already started contributing to this section. However, since there are many cooling technologies maybe you can work on another technology.

**Comment by laszewsk** [comment]
yes contribute to that. I suggest you look ate my notes.

i suggest to do water cooled doors also

**Comment by laszewsk** [comment]
Pulashti, when someone wants to contribute, simply add him to the assignee, i think you have access rights to do that. This way we do not forget who wants to contribute .... I added robludwig
