### ISSUE TITLE
Open: Develop an introduction to Go

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#48]

**Comment by laszewsk** [comment]
first review Monday Sept 17

**Comment by laszewsk** [comment]
url to section: 
you comment its finished.
than its reviewed. 
the reviewrs can ckose
there were issues

**Comment by laszewsk** [comment]
rewritten introduction by gregor
added to do statements that will be addressed in future
needs bib refernces
needs to be made to a great example for students

**Comment by laszewsk** [comment]
Pulashti educate Qianqian on bibtex refs. 
Show here a single one in her go titorial, than have her do the rest.

**Comment by bfeng** [comment]
Go introduction and some related sections updated: caba92d60d6be15308961f43ff1b9010f5b1ef90

#68: The bibtex references are not resolved yet.

**Comment by bfeng** [comment]
#68
