### ISSUE TITLE
Test issue from a Student

### ISSUE THREAD

**Issue by Vafa-Andalibi** [cloudmesh-community/book#54]
Submitting a new `issue` seems to be working fine on student's side! 
Test code: 
``` Python 
#! /usr/bin/python
print(Hello Cloud!)
``` 
---
Edit: New stuff after edit

**Comment by laszewsk** [comment]
This works.

Check out: https://github.com/cloudmesh-community/book/projects/1

**Comment by laszewsk** [comment]
I will not yet do this for all students but just testing this put with a small number of people including the tas
