### ISSUE TITLE
epub: use numbered Figure refernces

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#58]
Total effort 1h
- [ ] understand numbered figure refernces, see notation.md
- [ ] fix all **Figure** occurences in chapters/cloud/chameleon/heat.md
- [ ] fix all **Figure** occurences in chapters/cloud/chameleon/horizon.md
- [ ] fix all **Figure** occurences in chapters/cloud/chameleon/user-guide.md
- [ ] fix all **Figure** occurences in chapters/iaas/aws/aws.md
- [ ] fix all **Figure** occurences in chapters/iaas/azure/azure.md
- [ ] fix all **Figure** occurences in chapters/iaas/mapreduce/amazon-emr-2.md

**Comment by laszewsk** [comment]
reassigned to bo

**Comment by laszewsk** [comment]
figures must be cited as explained in notation.md

**Comment by bfeng** [comment]
@Tangqianq Please make sure all figures have correct labels, which I can cite later in the text.

**Comment by laszewsk** [comment]
incomplete reassigned to Bo
