### ISSUE TITLE
epub: organize haddop section

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#61]

**Comment by bfeng** [comment]
https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-hadoop.md
Updated.

**Comment by laszewsk** [comment]
what about filename incorrect

**Comment by laszewsk** [comment]
also add link to pagerenk example. Pulashti works on that

**Comment by bfeng** [comment]
> what about filename incorrect

What filename is incorrect?

**Comment by bfeng** [comment]
Which file should I link to?

Thanks,

Bo Feng

**Comment by laszewsk** [comment]
see the red circles

**Comment by laszewsk** [comment]
see epub, create a hyperlink via markdown to pagerank, I am sure you can fgrep for it
