### ISSUE TITLE
internal: bib: create bibtex entries for go-intro.md

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#68]
create bibtex entries for the file 

- chapters/prg/go/go-intro.md

and add them to

- bib/go.bib

Add the label to the md file and replace the [?]. See go-lang for an example. Once you finish a refernce, check it of in the following list

List:

- [x]  [Go cheat sheet](https://github.com/a8m/go-lang-cheat-sheet) [?].
- [x]  [The Little Go Book](http://openmymind.net/The-Little-Go-Book/) [?].
- [x]  [Learn Go in an Hour - Video](https://www.youtube.com/watch?v=CF9S4QZuV30) _2015-02-15_
- [x]  [Learning to Program in Go](https://www.youtube.com/playlist?list=PLei96ZX_m9sVSEXWwZi8uwd2vqCpEm4m6), a multi-part video training class [?].
- [x]  [Go By Example](http://gobyexample.com/) provides a series of
  annotated code snippets [?].
- [x]  [Learn Go in Y minutes](http://learnxinyminutes.com/docs/go/) is a
  top-to-bottom walk-through of the language [?].
- [x]  [Workshop-Go](https://github.com/sendwithus/workshop-go) - Startup
  Slam Go Workshop - examples and slides [?].
- [x]  [Go Fragments](http://www.gofragments.net/) - A collection of
    annotated Go code examples [?].
- [x]  [50 Shades of Go: Traps, Gotchas, Common Mistakes for New Golang Devs](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html) [?]
- [x]  [Free Go Language Workshop](https://www.frameworktraining.co.uk/go-language-free-training-workshop/) Framework Training is running regular free BYOD workshops in London, UK [?]
- [x]  [Golang Tutorials](http://golangtutorials.blogspot.com/2011/05/table-of-contents.html) - A free online class [?].
- [x]  [The Go Bridge Foundry](https://github.com/gobridge) [?] - A member of
  the [Bridge Foundry](http://bridgefoundry.org/) [?] family, offering a
  complete set of free Go training materials with the goal of
  bringing Go to under-served communities.
- [x]  [Golangbot](https://golangbot.com/learn-golang-series/) - Tutorials
  to get started with programming in Go [?].
- [x]  [Algorithms to Go](http://yourbasic.org/) - Texts about algorithms
  and Go, with plenty of code examples [?].
- [x]  [Go Language Tutorials](https://www.cybrhome.com/topic/go-language-tutorials) - List of popular sites, blogs and tutorials for learning Go language [?].
- [x]  [Golang Development Video Course](https://www.youtube.com/playlist?list=PLzUGFf4GhXBL4GHXVcMMvzgtO8-WEJIoY) - A growing list of videos focused purely on Go development [?].

**Comment by laszewsk** [comment]
- [ ]  [golang.org](http://golang.org/doc/#learning) [?].
- [ ]  [Go cheat sheet](https://github.com/a8m/go-lang-cheat-sheet) [?].
- [ ]  [The Little Go Book](http://openmymind.net/The-Little-Go-Book/) [?].
- [ ]  [Learn Go in an Hour - Video](https://www.youtube.com/watch?v=CF9S4QZuV30) _2015-02-15_
- [ ]  [Learning to Program in Go](https://www.youtube.com/playlist?list=PLei96ZX_m9sVSEXWwZi8uwd2vqCpEm4m6), a multi-part video training class [?].
- [ ]  [Go By Example](http://gobyexample.com/) provides a series of
  annotated code snippets [?].
- [ ]  [Learn Go in Y minutes](http://learnxinyminutes.com/docs/go/) is a
  top-to-bottom walk-through of the language [?].
- [ ]  [Workshop-Go](https://github.com/sendwithus/workshop-go) - Startup
  Slam Go Workshop - examples and slides [?].
- [ ]  [Go Fragments](http://www.gofragments.net/) - A collection of
    annotated Go code examples [?].
- [ ]  [50 Shades of Go: Traps, Gotchas, Common Mistakes for New Golang Devs](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html) [?]
- [ ]  [Free Go Language Workshop](https://www.frameworktraining.co.uk/go-language-free-training-workshop/) Framework Training is running regular free BYOD workshops in London, UK [?]
- [ ]  [Golang Tutorials](http://golangtutorials.blogspot.com/2011/05/table-of-contents.html) - A free online class [?].
- [ ]  [The Go Bridge Foundry](https://github.com/gobridge) [?] - A member of
  the [Bridge Foundry](http://bridgefoundry.org/) [?] family, offering a
  complete set of free Go training materials with the goal of
  bringing Go to under-served communities.
- [ ]  [Golangbot](https://golangbot.com/learn-golang-series/) - Tutorials
  to get started with programming in Go [?].
- [ ]  [Algorithms to Go](http://yourbasic.org/) - Texts about algorithms
  and Go, with plenty of code examples [?].
- [ ]  [Go Language Tutorials](https://www.cybrhome.com/topic/go-language-tutorials) - List of popular sites, blogs and tutorials for learning Go language [?].
- [ ]  [Golang Development Video Course](https://www.youtube.com/playlist?list=PLzUGFf4GhXBL4GHXVcMMvzgtO8-WEJIoY) - A growing list of videos focused purely on Go development [?].

**Comment by laszewsk** [comment]
reassigned to Bo

**Comment by laszewsk** [comment]
reassigned to Bo

**Comment by laszewsk** [comment]
what is progress?

**Comment by bfeng** [comment]
See commit:  e8482090bad2986197b5e7a4fa3a44a518c4f146
