### ISSUE TITLE
add mapreduce to syllabus

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#77]
file https://github.com/cloudmesh-community/book/blob/master/chapters/class/e516-syllabus-table.md

contains a large table. Add all section and subsections in order in a single line under mapreduce, mark them red till we release them

**Comment by laszewsk** [comment]
no progress, so reassigning to Gregor as we need it now

**Comment by laszewsk** [comment]
add more details to teh syllabus table

**Comment by tbalson** [comment]
This means update.md, 516 weekly update and table
